### PR TITLE
Feature/126 support for ocbc bank

### LINKED ISSUE #126: Support for OCBC Bank [SG]
Name of Bank: OCBC Bank 
Country: Singapore [SG]

Source: [fongming/OCBC-YNAB-Parser](https://github.com/fongming/OCBC-YNAB-Parser) 

```
[SG OCBC Bank, checking and credit card]
# source: Issue #126
Use Regex for Filename = True
Source Filename Pattern = TransactionHistory_[0-9]{12}
```

Note: The source code ([direct link](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L40)) determines bank transactions or credit card based on the presence of certain words, and there seem to be different number of header rows depending on bank transactions ([here](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L12)) or credit card ([here](https://github.com/fongming/OCBC-YNAB-Parser/blob/c3a5f9159a064d94799cfd9604213ff16af990d1/OCBC_YNAB_Parser.py#L31)) - but apparently the same default filename.

Master issue #21

### PR DESCRIPTION
**Pull request by nocalla**
Tracking pull request for #126. 

Fix #126.

### CODE REVIEW

**Comment by nocalla** [comment]
This isn't ready for merge yet, I'm just making this as an area to comment on the update. 

We need to replace the X in test file with random numbers just so tests work properly on it.

**Comment by nocalla** [comment]
@njunxuan - your plugin looks like it makes sense. Is it parsing your input file correctly?

**Comment by njunxuan** [comment]
Yes it is working fine on my end. Thanks for changing the XX values to numbers! What are the next steps before this can be merged?

**Comment by nocalla** [comment]
I'm happy to merge this anyway. Our automated tests are complaining that it
reduces the amount of test coverage, but that's an issue we need to work on
separately anyway. Thanks for the input! It's nice when people do the
legwork for their own bank themselves!

**Comment by nocalla** [comment]
It might be, but we'll have to work out the best testing approach anyway.

**Comment by njunxuan** [comment]
No problem. Thanks for all the help!

**Pull request merged**
