### PR TITLE
Cosmetics

### PR DESCRIPTION
**Pull request by torbengb**
I want to pull the latest code into my branch and clean up my modifications. Then I'll merge it back into master.

### CODE REVIEW

**Comment by nocalla** [comment]
You're actually merging into master with this pull, not from master into cosmetics as you state above.

**Comment by torbengb** [comment]
Really?! Thanks for keeping me straight! I'm confused now because in the browser is says:

> Cosmetics #70
>  Open	torbengb  wants to merge 5 commits into master from Cosmetics

While I have your attention: a question -- I'd like to add a newline between each processed file, and at the start and end of the entire processing. I feel it makes the whole thing much more readable on the command line.  Any good arguments against that?

**Comment by nocalla** [comment]
Exactly- into master.

Nope, doesn't bother me. I'll be running it from the batch file, so won't
even really see the output myself!

**Comment by torbengb** [comment]
*I am an idiot.*

*I am an idiot.*

*I am an idiot.*

*I am an idiot.*

**Pull request closed without merging**
