### PR TITLE
Merge in njunxuan's fork.

### PR DESCRIPTION
**Pull request by nocalla**

### CODE REVIEW

**Comment by torbengb** [comment]
I appreciate the contribution! But .... 

The test file is smaller than [the one in his own repo](https://github.com/njunxuan/bank2ynab/blob/9b90c2cdaeaab6ed92667f104107e8c0a306c0a9/test-data/TransactionHistory_20180418043121.csv), and more importantly it uses `XX.XX` instead of actual amounts. I'd like to see a better sample CSV file. 

As for the format config, and the "empty date value check", I think it's premature to merge this. We need to reach a consensus on #126 first.

Based on this, I think we should postpone this merge for a little while longer.

**Comment by nocalla** [comment]
This is a merge into a test branch, not develop, don't worry.

**Comment by nocalla** [comment]
I just wanted to have a start point for the plugin.

**Comment by nocalla** [comment]
Also the test file in his own fork was just updated after I merged. I'll keep this branch up to date with his developments.

**Comment by torbengb** [comment]
I stand corrected then :-)

**Pull request merged**
