### PR TITLE
Added UK Cooperative Bank format

### PR DESCRIPTION
**Pull request by toyg**

### CODE REVIEW

**Comment by torbengb** [comment]
Thanks for this! Is there a reason why you didn't also add the file name pattern? I saw the other ticket about the UK sort code that would be meaningful to add (without the account number, obviously).

**Comment by toyg** [comment]
Well, because it would be different for everyone... do you want me to add something suggesting values that should be changed, e.g.
```
Source Filename Pattern = yoursortcode_youraccountnum_
```

**Comment by torbengb** [comment]
Oh, I thought the sort code would be the same for all customers of UK Cooperative Bank, but now I guess it's a separate code for each branch office then? Maybe the first two or three digits in the sort code are static for all branch offices? That's when wildcard matching could help us. If not even that, then I you did all you could.

@nocalla isn't the filename pattern a requirement for the script? Without that, the script won't be able to match any files against this section?

**Comment by toyg** [comment]
There is a constant for the Coop sort codes, which is the starting "08". I guess I could add that.

**Comment by nocalla** [comment]
@torbengb Yes. Without matching filename, nothing happens. 08 is too vague I would say. Workaround is to either manually rename export file or explicitly have user use format as @toyg specified above with Source Filename Pattern = yoursortcode_youraccountnum_. Wildcards are the actual solution.

**Comment by nocalla** [comment]
Considering the feasibility of including a regex in the config for source filename. Thoughts?

**Comment by torbengb** [comment]
I don't like regex because it looks like black magic voodoo to me (just like that ominous `vi` editor). But I recognize the power of regex and I think it would be a very useful addition.

**Comment by nocalla** [comment]
Might as well merge this for now and add regex when it's sorted.

**Pull request merged**
