### PR TITLE
Python 2 Compatibility

### PR DESCRIPTION
**Pull request by nocalla**

### CODE REVIEW

**Comment by nocalla** [comment]
Works with no issue on Windows using Python 3.5.0. Including on my updated BOI test file, which has umlauts in it. (Pushed updated test file)

**Comment by torbengb** [comment]
I've tested all branches just now on Linux, and they all seem to fail on py2 and work on py3.

It would be so much easier if we just decided to give up on py2 but that would mean abandoning users, so that won't fly.

**Comment by nocalla** [comment]
What's the current error?

**Comment by torbengb** [comment]
As per right now, 
on `master` branch:

    Your specified download directory was not found: /home/torben/Downloadsx
    Parsing file: elbi_umsaetze_20171024191306.csv
    Using format: AT Raiffeisen Bank
    Traceback (most recent call last):
      File "bank2ynab.py", line 179, in <module>
        main()
      File "bank2ynab.py", line 169, in main
        output = clean_data(file)
      File "bank2ynab.py", line 73, in clean_data
        transaction_reader = csv.reader(transaction_file, delimiter = delim)
    TypeError: "delimiter" must be string, not unicode

On `issue-#25` branch: 

    Your specified download directory was not found: /home/torben/Downloadsx
    Parsing file: elbi_umsaetze_20171024191306.csv
    Using format: AT Raiffeisen Bank
    Traceback (most recent call last):
      File "bank2ynab.py", line 221, in <module>
        main()
      File "bank2ynab.py", line 210, in main
        output = clean_data(file)
      File "bank2ynab.py", line 90, in clean_data
        transaction_reader = csv.reader(transaction_file, delimiter=delim)
    TypeError: "delimiter" must be string, not unicode

On `better-output` branch: 

    Your specified download directory was not found: /home/torben/Downloadsx
    Parsing file: elbi_umsaetze_20171024191306.csv
    Using format: AT Raiffeisen Bank
    Traceback (most recent call last):
      File "bank2ynab.py", line 184, in <module>
        main()
      File "bank2ynab.py", line 174, in main
        output = clean_data(file)
      File "bank2ynab.py", line 78, in clean_data
        transaction_reader = csv.reader(transaction_file, delimiter = delim)
    TypeError: "delimiter" must be string, not unicode

These lines 73 and 90 and 78 respectively are actually the same code, just shifted due to other code above.

**Comment by nocalla** [comment]
So...the same error every time. The delimiter as unicode thing. Ok, there
must be a way to fix that. Issuing that in specific.

**Comment by torbengb** [comment]
Great - now, _apart_ from that issue #59, can we merge all those branches together now? I'm getting confused :)

**Comment by nocalla** [comment]
Redundant now that I merged the py2 branch into master!

**Pull request closed without merging**
