### PR TITLE
Fix for bug #182

### LINKED ISSUE #182: Output corrupt because filename pattern matched two formats
Script language: Python 2.7.12
Operating system: Linux Ubuntu
OS Version: 17.04

What did you DO? (steps to reproduce)
- downloaded CSV file from Raiffeisen (we support that format)
- altered the config file to *not* delete the input file after processing
- started the program.

What did you EXPECT to happen?
- one input file converted to YNAB format.

What ACTUALLY happened?
- input file was converted (presumably success)
- input file was not deleted (because I configured that)
- input file matched another format: Format: DE Deutsche Kreditbank checking (bug?)
- output file was overwritten with new conversion (this created a YNAB CSV file that only contained the header row)
- input file was deleted! (in my testing I should probably change the main config rather than for just 1 format)

Can you provide other helpful information?
Output: 

```
$ python bank2ynab.py
bank2ynab 1.1.0-mytestbranch using Python 2.7.12

Format: AT Raiffeisen Bank

Error: Can't find download path: c:\users\example-username\Downloads
Trying default path instead:	 /home/torben/Downloads

Parsing input file:  /home/torben/Downloads/elbi_umsaetze_20180226165906.csv
Parsed 79 lines
Writing output file: /home/torben/Downloads/fixed_elbi_umsaetze_20180226165906.csv

Format: DE Deutsche Kreditbank checking

Error: Can't find download path: c:\users\example-username\Downloads
Trying default path instead:	 /home/torben/Downloads

Parsing input file:  /home/torben/Downloads/elbi_umsaetze_20180226165906.csv
Parsed 0 lines
Writing output file: /home/torben/Downloads/fixed_elbi_umsaetze_20180226165906.csv
Removing input file: /home/torben/Downloads/elbi_umsaetze_20180226165906.csv

Done! 2 files processed.
```

### PR DESCRIPTION
**Pull request by torbengb**
This change should fix #182 because format collisions don't overwrite existing output anymore.

It's a small change to the code, and made the file counter global.  
Also, a tiny nitpick about the formats slipped in. Nevermind.

### CODE REVIEW

**Comment by nocalla** [comment]
I was about to take my computer apart for moving and I saw a solution to this so couldn't resist!

**Comment by torbengb** [comment]
Now, you say "solution" when in reality I had created something of a trainwreck there - and *that* is what you couldn't resist ;-) but I'm happy you like the idea.

**Comment by nocalla** [comment]
Fix #182. Rock and roll.

**Comment by nocalla** [comment]
I'm unplugging my computer for the move now, so don't expect anything constructive for at least a day!

**Comment by torbengb** [comment]
I wish you lots of success! TTYL!

**Pull request merged**
